### ISSUE TITLE
Not building on Arch Linux

### ISSUE THREAD

**Issue by joshproehl** [taffybar/gtk-strut#4]
Arch Linux AUR package [haskell-gtk-strut](https://aur.archlinux.org/packages/haskell-gtk-strut/) is not building. This appears to be due to the fact that @LeifW's recent patch for GHC 8.6 is not included in the 0.1.2.1 being pulled from Hackage.

Is a new version going to be released and put on Hackage so the AUR package can be flagged/updated?

**Comment by colonelpanic8** [comment]
I'll try to make a release soon.
